### ISSUE TITLE
Is this repository suitable for keywords extraction and chinese word sementation? 

### ISSUE THREAD

**Issue by Jiakui** [dwadden/dygiepp#1]
Hi ,

I thinks span representation is a great idea.  Do you think the span representation is suitable for keywords extraction and chinese word sementation? 

Thanks!

**Comment by dwadden** [comment]
@Jiakui just letting you know that the code runs now. If you pull it and follow the instructions in the README, you should be able to train a model. To adapt for Chinese word segmentation, you'll probably want to adapt the NER module https://github.com/dwadden/dygiepp/blob/master/dygie/models/ner.py.
