### ISSUE TITLE
Creating the ACE Event 05 dataset

### ISSUE THREAD

**Issue by mikebrules** [dwadden/dygiepp#100]
Hello - sorry for the Hello World issue, but I'm trying to follow the instruction on generating the ACE Event dataset, but I can't find the path to the ACE data. In [this](https://github.com/dwadden/dygiepp#ace05-event) section it states

`bash ./scripts/data/ace-event/collect_ace_event.sh [path-to-ACE-data].`

.....but the [path-to-ACE-data] is not specified, and I can't find anything documented. Just running the script produces the error 

`cannot access '/data/English': No such file or directory`

...which is correct, it isn't there. What should the path be please?

Thanks in advance

**Comment by dwadden** [comment]
Unfortunately, that is correct, ACE is not public. I'm not sure about the exact price. Sorry about that! The other datasets as far as I remember are public and the data processing scripts should download them.

**Comment by dwadden** [comment]
Unfortunately, that is correct, ACE is not public. I'm not sure about the exact price. Sorry about that! The other datasets as far as I remember are public and the data processing scripts should download them.
