### ISSUE TITLE
No module named 'dygie'

### ISSUE THREAD

**Issue by vijini** [dwadden/dygiepp#101]
@e3oroush: When I tried running 
"import spacy
from dygie.spacy_interface.spacy_interface import DygieppPipe"
                                                                                                               in Colab, it mentions that there is no module named dygie. Also I tried installing dygie using pip or apt. But neither worked. Can you please advice me on this? Thanks.

**Comment by e3oroush** [comment]
Hi
You should add dygie project folder to your python system path. As an example, [conda develop](https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-develop.html) can do it for you. Or you can simply add the directory manually to your `sys.path`. See [this](https://stackoverflow.com/a/59903590/1430342) answer to find out more about adding custom packages to your python path.

**Comment by dwadden** [comment]
Thanks for fielding this, @e3oroush. @vijini, the [Dependencies](https://github.com/dwadden/dygiepp#dependencies) section of the `README` has instructions on what you need to do to get set up.
