### ISSUE TITLE
where is the ACE-data?

### ISSUE THREAD

**Issue by baiziyuandyufei** [dwadden/dygiepp#115]

**Comment by serenalotreck** [comment]
@baiziyuandyufei unfortunately obtaining the ACE dataset requires a paid license, so you have to obtain the dataset yourself before you can use the code in this repo (mentioned in #100)

**Comment by serenalotreck** [comment]
I haven't actually done it myself because the last I checked it cost around $2000, but here's the link that should guide you through getting it: https://catalog.ldc.upenn.edu/LDC2006T06

**Comment by dwadden** [comment]
Thanks @serenalotreck for explaining. I'll close this.
