### ISSUE TITLE
How to print the prediction of the trained models?

### ISSUE THREAD

**Issue by vuducanh0802** [dwadden/dygiepp#116]
Hi,

Thanks for the detailed code and careful instructions. I would like to print out the prediction of the trained models for visualization. May I ask whether you had the code for this?

**Comment by dwadden** [comment]
Unfortunately, i don't think the code directly supports this. You can certainly save the predictions out to a file. Other than that, you can always insert `print` statements to view the [output_dict](https://github.com/dwadden/dygiepp/blob/master/dygie/models/dygie.py#L269) of predictions.

**Comment by vuducanh0802** [comment]
Thank you for the response !
