### ISSUE TITLE
parse_ace_event.py "ipdb" debugging

### ISSUE THREAD

**Issue by Eliauk-TiAmo** [dwadden/dygiepp#121]
“python ./scripts/data/ace-event/parse_ace_event.py default-settings ”，Jump all the way to "ipdb" debugging while executing this step

**Comment by dwadden** [comment]
Can you confirm that you've run the setup instructions as described in the repo?

**Comment by Eliauk-TiAmo** [comment]
What you said is correct. When I was downloading an installation package, a version number was automatically updated. Now that this issue has been resolved, thank you for your reply and help!
