### ISSUE TITLE
override template.DyGIE values from command line

### ISSUE THREAD

**Issue by jbdel** [dwadden/dygiepp#124]
Hello,

Thank you for this repository.

Is there a way to override a value from command line? I tried:

```
allennlp train "training_config/mymodel.jsonnet" \
    --serialization-dir "models/mymodel" \
    --include-package dygie \
    --evaluate-on-test \
    -o '{"data_paths": {"train": "new_path/train.jsonl", "validation": "new_path/dev.jsonl", "test": "new_path/test.jsonl"}}'
```
returns:

`allennlp.common.checks.ConfigurationError: Extra parameters passed to TrainModel: {'data_paths': {'test': 'new_path/test.jsonl', 'train': 'new_path/train.jsonl', 'validation': 'new_path/dev.jsonl'}}`

Thanks in advance!

**Comment by jbdel** [comment]
for someone interested:

`--include-package dygie \
    -o '{
        "train_data_path": "'"$DATA_PATH"'/train.jsonl",
        "validation_data_path": "'"$DATA_PATH"'/dev.jsonl",
        "test_data_path": "'"$DATA_PATH"'/test.jsonl"
    }'`

**Comment by dwadden** [comment]
Thanks, this is helpful!
