### ISSUE TITLE
How to use my dataset

### ISSUE THREAD

**Issue by rockman1989** [dwadden/dygiepp#19]
I want to use my dataset,  my data include *.ann and *.txt. How to convert data into project input data？ use tools? I hope you can give me some advice.

**Comment by dwadden** [comment]
We wrote different scripts to deal with different dataset formats. They're all in [this folder](https://github.com/dwadden/dygiepp/tree/master/scripts/data). 

If you post an example `.ann` and `.txt` file in this thread, I can try to offer some more specific ideas.

**Comment by dwadden** [comment]
Closing for now. If you're stuck, send along an example and we can figure something out.
