### ISSUE TITLE
Coreference propagation on ACE05

### ISSUE THREAD

**Issue by khuangaf** [dwadden/dygiepp#21]
In the paper you mention as ACE does not have coreference annotation, you use OntoNotes for coreference propagation. I was wondering if it is possible to predict coreference on ACE using the current trained model?

**Comment by dwadden** [comment]
Unfortunately no. Coref didn't help at all on ACE, so we didn't end up releasing the co-training code. I'll try to dig up the ontonotes data to see if I can train a model for this, but I'm not sure I've got it in the required format anymore.

**Comment by khuangaf** [comment]
I see. Thank you very much!

**Comment by khuangaf** [comment]
I have one quick question regarding ACE05 coreference resolution. In the paper you states that "the ACE
data set lacks coreference annotations". However, the original ACE05 annotation contains <entity> and <entity_mention> tags. I am wondering why it does not count as coreference for all <entity_mention> under the same <entity> tag?

**Comment by dwadden** [comment]
Hmm that's a great point, I hadn't thought of that. I'd definitely welcome a PR to preprocess the data such that ACE mentions are linked via coreference clusters.

**Comment by serenalotreck** [comment]
Just wanted to clarify -- the current ACE05 relations model doesn't include coreference propogation, so it's equivalent to the "lightweight" versions of the other datasets' models?

Thanks!

**Comment by dwadden** [comment]
Yep, that's correct!
