### ISSUE TITLE
Keyword extraction from scientific abstracts

### ISSUE THREAD

**Issue by anaerobeth** [dwadden/dygiepp#22]
Hi! I'm interested in using `dygiepp` for automatically generating keywords from scientific abstracts, and testing how it performs compared to Textacy algorithms for keyword extraction (for context, see https://github.com/Mini-Conf/Mini-Conf/issues/34). 

I'm looking to preprocess sample abstracts in https://github.com/anaerobeth/dygiepp/tree/keyword-extraction/data/miniconf/raw_data to generate suitable .txt and .ann files for use in making predictions using the pretrained scierc lightweight model. Can you provide some guidance on how to get started with this task? Thanks!

**Comment by dwadden** [comment]
Thanks for the interest!

Are they abstracts unlabeled? If so, this should be fairly simple.

**Comment by dwadden** [comment]
Done. See [Working with new datasets](https://github.com/dwadden/dygiepp/blob/master/README.md#working-with-new-datasets) and [Formatting a new dataset](https://github.com/dwadden/dygiepp/blob/master/DATA.md#formatting-a-new-dataset). Closing for now; feel free to reopen if this doesn't solve your problem.

**Comment by anaerobeth** [comment]
@dwadden Thanks for your help on this. We used DyGIE++ to autogenerate keywords for the papers in ACL 2020  (https://virtual.acl2020.org/papers_vis.html) .

**Comment by dwadden** [comment]
Great, glad it worked!
