### ISSUE TITLE
ace05_event.jsonnet embeddings shape size error

### ISSUE THREAD

**Issue by ndobb** [dwadden/dygiepp#25]
First, thanks for all your great work!

I've put my own labeled data in the DyGIE++ format, following the instructions in (https://github.com/dwadden/dygiepp/blob/master/DATA.md). I was able to successfully train the Relation extractor fine using the `ace05_best_relation_bert.jsonnet` config, with quite good performance. 

When I next tried to train for Events using `ace05_event.jsonnet`, however, I ran into the following error:
![image](https://user-images.githubusercontent.com/10424962/87591750-a1816b80-c69d-11ea-8a12-1cba3cf7427f.png)

Following the comments in https://github.com/dwadden/dygiepp/blob/master/training_config/template_dw.libsonnet#L88, I then made a copy of `ace05_event.jsonnet`, changing the `n_trigger_labels` and `n_ner_labels` values to reflect my own dataset counts, ie:

**ace05_event_copy.jsonnet**
```
  n_trigger_labels: 28,    // prev: 34
  n_ner_labels: 103,       // prev: 8
```

However I'm still getting the error, `RuntimeError: shape '[-1, 2745]' is invalid for input of size 5601840` in https://github.com/dwadden/dygiepp/blob/master/dygie/models/events.py#L553.

**Comment by ndobb** [comment]
After some debugging, I found that this was an off-by-one error, and needed to include empty labels, so `n_ner_labels` = 103+1. This solved the issue.

**Comment by dwadden** [comment]
Great, glad it worked. Let me know if you're still stuck on the other issue you posted about.
