### ISSUE TITLE
English : no such file or directory

### ISSUE THREAD

**Issue by wingz1** [dwadden/dygiepp#28]
Hi,
Where do you get the "English" file or directory for ace05.
After running get_corenlp.sh and then subsequently running get_ace05.sh I get an error:
cp: cannot stat ‘./scripts/data/ace05/common/*/English’: No such file or directory
run.zsh:4: no matches found: English/*/timex2norm/*.sgm
etc

Thanks for any help.

**Comment by dwadden** [comment]
You need to provide `get_ace_05.sh` with the path to the folder containing your ACE data distribution, which should have a subfolder `common/English`. Can you share the directory structure of your ACE data distribution here?

**Comment by wingz1** [comment]
Sure. After running the provided get_ace_05.sh, the English directory is missing i.e.  the data/ace05/common/English folder.
I wonder if it was taken away from the site it is supposed to be downloaded from.

Specifically, the directory structure looks like this in ./data
> pwd
[local_path]/dygiepp/scripts/data
> ls ace05
common/  get_corenlp.sh  preprocess/
> ls ace05/common
conll2txt.py  dep2so.prl  fix_sentence_break.py  props_fixed  props_ssplit  standoff.py  stanford-corenlp-full-2015-04-20/  stanford-postagger-2015-04-20/
> ls ace05/preprocess/
ace2ann.py  ace2json.py  run.zsh  split/  train_list  train_list_fixed

**Comment by dwadden** [comment]
The `get_ace_05.sh` script needs to be invoked with an argument specifying the path to the ACE data distribution, for example `get_ace_05.sh [path-to-ace-distribution]`. The ACE data distribution is not publicly available. So, it's up to you to download the ACE data, put it in a folder somewhere, and point the script at it.

Let me know if this clears things up.

**Comment by wingz1** [comment]
Yep, thanks!
