### ISSUE TITLE
Multi-token triggers for event extraction

### ISSUE THREAD

**Issue by GillesJ** [dwadden/dygiepp#31]
I want to run the event extraction pipeline on my own dataset of ACE/ERE-like events.
The events have multi-token and discontinuous trigger spans.

I have not yet dived deep into the model code, but was hoping for some ideas how to adapt it to multi-token spans.
- Is it possible with the current approach to model multi-token triggers?
- Is it possible to model discontinuous triggers?
- Which functions in the code are prime candidates for adaptation?

For now, I will parse and use the head token of the trigger annotations, but due to the discriminative and content-rich nature of my multi-token triggers I expect it to hurt trigger classification.

Thank you for making this code available and supporting it. Having a SotA event extraction system available really helps my research.

**Comment by dwadden** [comment]
Sorry for the delayed response... EMNLP rebuttals.

- Multi-token is definitely doable.
- Discontinuous is tricky.

Let me do a bit of work to get event extraction running on the `allennlp-v1` branch. It will be easier to make the changes there, the code is much cleaner. Once that's done I'll add another message here with details on where to make changes.

**Comment by dwadden** [comment]
Great, this will be a really useful addition. Keep me posted.

**Comment by nlp-sudo** [comment]
Was there any progress made on this? If yes, would it be possible to get a pre-trained model which can predict multi-token triggers?

**Comment by GillesJ** [comment]
> Was there any progress made on this? If yes, would it be possible to get a pre-trained model which can predict multi-token triggers?

I have been pre-occupied with other things, but will work on it the coming days.

I am not planning on training and releasing a pre-trained model. The ACE05-Event dataset is single-token, a common general-news geo-political event dataset is ERE which is multi-token. ERE currently lacks any utility scripts for parsing and pre-processing.
Maybe OneIE has pre-processor scripts to parse ERE to DYGIE format, I haven't checked yet.

I am mainly implementing this for use with my own financial event dataset, but I will keep you posted here if I decide to work on ERE.

**Comment by nlp-sudo** [comment]
Ok. Thanks for the information.

**Comment by GillesJ** [comment]
I added multi-token trigger support in PR https://github.com/dwadden/dygiepp/pull/48.

Some thoughts:
- Distance embeddings for the trig-arg-contextualization were indeed a good default.
- Documentation should still be updated to reflect changes.
- I stuck with the approach in which annotations exceeding the max_span_width and max_trigger_span_width are simply ignored in the datasetreader and thrown out. Maybe a more sane default is to truncate these spans to the max_width?

**Comment by dwadden** [comment]
Closing this as well.
