### ISSUE TITLE
SciERC datset

### ISSUE THREAD

**Issue by sundarvara1** [dwadden/dygiepp#33]
Hi,
In the SciERC dataset (scierc.raw.tar.gz), for each abstract doc, there are three files - .txt (which is the raw text of the abstract), .ann (which captures the annotations for entities, relations, corefs). There is also a third file .xml.txt associated with each doc abstract - this seems to contain some details including the pos, parse tree/dependency information. What is this xml file and how is this to be generated? What is the process to create this if we want to bring in our own domain-specific documents to be trained on dygiee++?
Would appreciate a quick response, thanks,
Sundar

**Comment by dwadden** [comment]
Hi Sundar,

I actually don't know much about the raw SciERC data. Is there some reason that working with the processed `json` doesn't work for you?

There is documentation on the data format used for dygie++, and the steps required to convert your own dataset, here: https://github.com/dwadden/dygiepp/blob/master/doc/data.md.

Let me know if this doesn't work for you.

Dave
