### ISSUE TITLE
Model tests are failing because of missing `span_emb_dim` key

### ISSUE THREAD

**Issue by knuser** [dwadden/dygiepp#4]
All models tests are failing with message: `allennlp.common.checks.ConfigurationError: 'key "span_emb_dim" is required at location "coref."'`

```
(dygie) ~/ml/dygiepp/dygie(debugging) $ python -mpytest tests
================================================= test session starts ==================================================
platform linux -- Python 3.7.5, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /home/konrad/ml/dygiepp/dygie, inifile: pytest.ini
plugins: flaky-3.6.1
collected 15 items                                                                                                     

tests/data/ie_json_test.py ........                                                                              [ 53%]
tests/models/coref_test.py F                                                                                     [ 60%]
tests/models/dygie_test.py F                                                                                     [ 66%]
tests/models/relation_test.py FFFFF                                                                              [100%]
[...]
```

**Comment by dwadden** [comment]
Thanks for the heads up. The tests are very out of date, I'll work on updating.

**Comment by mojesty** [comment]
Also, in test configs there is no `events` key. I tried to add it manually from some actual config `scibert_ner_processed_data_0_rel_prop_3_...`, but then some other key `context_attention` was missing as well, so I'm giving up my attempts to fix it myself. 

@dwadden  it's really cool that you've written test configs in the first place, I'm looking forward when you'll fix them!

**Comment by dwadden** [comment]
Unfortunately the unit tests are probably going to fail fo a while. I'm going to close this.
