### ISSUE TITLE
Deploy as a REST service

### ISSUE THREAD

**Issue by navraj28** [dwadden/dygiepp#43]
Hello there!
    Can you recommend a way to deploy Dygiepp as a REST API.
Thanks,
NR

**Comment by dwadden** [comment]
Hmm good question, I'm not really sure. The AllenNLP predict https://docs.allennlp.org/master/api/commands/predict/ command can be used for bulk json-to-json predictions, and DyGIE can be hooked into this: https://github.com/dwadden/dygiepp/blob/master/dygie/predictors/dygie.py. 

My best advice is to explore the AllenNLP docs and see if there's some way to set up a REST API. If you get one working, let me know!
