### ISSUE TITLE
How to make inferences from the pretrained model

### ISSUE THREAD

**Issue by foodiehack** [dwadden/dygiepp#47]
I have not yet dived deep into the model code. I ran the allennlp predict as mentioned in the docs. It printed the inferences in the terminal. So is there any way to predict the relations,events etc from the shell.
A demo in Jupyter Notebook will be very useful.

**Comment by dwadden** [comment]
There's an `--output-file` flag that you can use to specify where the json results should go. This is described in the README: https://github.com/dwadden/dygiepp#making-predictions-on-existing-datasets.
