### ISSUE TITLE
Dcoker Build Fail

### ISSUE THREAD

**Issue by Yuichi-Nakababayashi** [dwadden/dygiepp#50]
I cloned this repository from master(main) branch, but I saw the following error message.
=```
> [internal] load build definition from Dockerfile                                                                                                                                                             0.2s
 => => transferring dockerfile: 3.33kB                                                                                                                                                                           0.1s
 => [internal] load .dockerignore                                                                                                                                                                                0.2s
 => => transferring context: 443B                                                                                                                                                                                0.1s
 => [internal] load metadata for docker.io/pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel                                                                                                                           6.2s
 => [auth] pytorch/pytorch:pull token for registry-1.docker.io                                                                                                                                                   0.0s
 => CANCELED [ 1/29] FROM docker.io/pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel@sha256:ccebb46f954b1d32a4700aaeae0e24bd68653f92c6f276a608bf592b660b63d7                                                        122.3s
 => => resolve docker.io/pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel@sha256:ccebb46f954b1d32a4700aaeae0e24bd68653f92c6f276a608bf592b660b63d7                                                                     0.0s
 => => sha256:bb833e4d631feff31ab57559d64617ad895d3ae7f45fdb651f9ba2df50b183b7 10.06kB / 10.06kB                                                                                                                 0.0s
 => => sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1 845B / 845B                                                                                                                       0.0s
 => => sha256:ee9b457b77d047ff322858e2de025e266ff5908aec569560e77e2e4451fc23f4 184B / 184B                                                                                                                       0.0s
 => => sha256:ccebb46f954b1d32a4700aaeae0e24bd68653f92c6f276a608bf592b660b63d7 3.05kB / 3.05kB                                                                                                                   0.0s
 => => sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff 35.36kB / 35.36kB                                                                                                                 0.0s
 => => sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c 26.69MB / 26.69MB                                                                                                                 0.0s
 => => sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4 162B / 162B                                                                                                                       0.0s
 => => sha256:d8f1569ddae616589c5a2dabf668fadd250ee9d89253ef16f0cb0c8a9459b322 7.22MB / 7.22MB                                                                                                                   0.0s
 => => sha256:85386706b02069c58ffaea9de66c360f9d59890e56f58485d05c1a532ca30db1 8.45MB / 8.45MB                                                                                                                   0.0s
 => => sha256:be4f3343ecd31ebf7ec8809f61b1d36c2c2f98fc4e63582401d9108575bc443a 77.59MB / 688.74MB                                                                                                              123.2s
 => => sha256:30b4effda4fdab95ec4eba8873f86e7574c2edddf4dc5df8212e3eda1545aafa 90.18MB / 820.84MB                                                                                                              123.2s
 => => sha256:b398e882f4149bf61faa8f2c1d47a4fe98b8fe1b2c9379da1d58ddc54fe67cf0 110.10MB / 532.41MB                                                                                                             123.2s
 => => extracting sha256:7ddbc47eeb70dc7f08e410a6667948b87ff3883024eb41478b44ef9a81bf400c                                                                                                                       15.6s
 => => extracting sha256:c1bbdc448b7263673926b8fe2e88491e5083a8b4b06ddfabf311f2fc5f27e2ff                                                                                                                        0.0s
 => => extracting sha256:8c3b70e3904492c753652606df4726430426f42ea56e06ea924d6fea7ae162a1                                                                                                                        0.0s
 => => extracting sha256:45d437916d5781043432f2d72608049dcf74ddbd27daa01a25fa63c8f1b9adc4                                                                                                                        0.0s
 => => extracting sha256:d8f1569ddae616589c5a2dabf668fadd250ee9d89253ef16f0cb0c8a9459b322                                                                                                                        5.3s
 => => extracting sha256:85386706b02069c58ffaea9de66c360f9d59890e56f58485d05c1a532ca30db1                                                                                                                        2.7s
 => => extracting sha256:ee9b457b77d047ff322858e2de025e266ff5908aec569560e77e2e4451fc23f4                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                                              122.3s
 => => transferring context: 903.71MB                                                                                                                                                                          122.1s
 => CACHED [ 2/29] RUN mkdir /dygiepp                                                                                                                                                                            0.0s
 => CACHED [ 3/29] RUN apt-get update &&     apt-get -y install gcc make sqlite3                                                                                                                                 0.0s
 => CACHED [ 4/29] RUN conda create --name dygiepp python=3.7 -y                                                                                                                                                 0.0s
 => CACHED [ 5/29] RUN conda install -c conda-forge jsonnet -y                                                                                                                                                   0.0s
 => CACHED [ 6/29] COPY requirements.txt /tmp/requirements.txt                                                                                                                                                   0.0s
 => CACHED [ 7/29] RUN pip install -r /tmp/requirements.txt                                                                                                                                                      0.0s
 => CACHED [ 8/29] RUN conda create --name ace-event-preprocess python=3.7 -y                                                                                                                                    0.0s
 => CACHED [ 9/29] COPY scripts/data/ace-event/requirements.txt /tmp/ace-prep-requirements.txt                                                                                                                   0.0s
 => CACHED [10/29] RUN pip install -r /tmp/ace-prep-requirements.txt                                                                                                                                             0.0s
 => CACHED [11/29] RUN python -m spacy download en                                                                                                                                                               0.0s
 => CACHED [12/29] RUN apt-get install openjdk-8-jdk openjdk-8-jre wget unzip -y                                                                                                                                 0.0s
 => CACHED [13/29] COPY scripts/data/ace05/get_corenlp.sh /tmp/get_corenlp.sh                                                                                                                                    0.0s
 => CACHED [14/29] RUN cd /dygiepp/ && bash /tmp/get_corenlp.sh                                                                                                                                                  0.0s
 => CACHED [15/29] RUN conda install -c conda-forge zsh -y                                                                                                                                                       0.0s
 => CACHED [16/29] RUN apt-get install unzip wget -y                                                                                                                                                             0.0s
 => CACHED [17/29] COPY scripts/data/shared /dygiepp/scripts/data/shared                                                                                                                                         0.0s
 => CACHED [18/29] COPY scripts/data/get_scierc.sh /tmp/get_scierc.sh                                                                                                                                            0.0s
 => CACHED [19/29] COPY dygie /dygiepp/dygie                                                                                                                                                                     0.0s
 => CACHED [20/29] RUN cd /dygiepp && bash /tmp/get_scierc.sh                                                                                                                                                    0.0s
 => CACHED [21/29] RUN apt-get install wget -y                                                                                                                                                                   0.0s
 => CACHED [22/29] COPY scripts/pretrained/get_dygiepp_pretrained.sh /tmp/get_dygiepp_pretrained.sh                                                                                                              0.0s
 => CACHED [23/29] RUN cd /dygiepp && bash /tmp/get_dygiepp_pretrained.sh                                                                                                                                        0.0s
 => ERROR [24/29] COPY scripts/pretrained/get_scibert.py /tmp/get_scibert.py                                                                                                                                     0.0s
------
 > [24/29] COPY scripts/pretrained/get_scibert.py /tmp/get_scibert.py:
------
failed to compute cache key: "/scripts/pretrained/get_scibert.py" not found: not found
```

Looking forward to hearing from you soon!

**Comment by dwadden** [comment]
Sorry for the slow response, I've been on vacation. The docker container was contributed by @GillesJ. If you're still having issues, feel free to reopen and maybe he can help.

**Comment by GillesJ** [comment]
Apparently, the `get_scibert.py` script has been removed from the main branch. Either I can add it back in or I remove those lines from the Dockerfile.

@dwadden was there a reason `get_scibert.py` was removed or was it accidental?

**Comment by dwadden** [comment]
It was actually on purpose. In the updated code, Huggingface transformers takes care of downloading and storing the models, so there's no need for a dedicated script to accomplish this.

**Comment by Yuichi-Nakababayashi** [comment]
@dwadden @GillesJ 
Thanks a lot for giving me a reply.
I've downloaded and stored the models, and I could successfully run an allennlp script.
Thank's a lot for your help!

**Comment by dwadden** [comment]
Glad it worked!
