### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by laiviet** [dwadden/dygiepp#52]
Hi,

I am training on a document of 40 sentences. some are long.
Do you have some advices to  lower the GPU memory use  (e.g. batch size (I cannot find the params as I am not familiar with allennlp) and sentence length)

I got out of memory in a 32GB Nvidia GPU.

Thanks

**Comment by laiviet** [comment]
I have to split the document into two pieces each has 20 sentences.

**Comment by dwadden** [comment]
Splitting the documents sounds like the right thing to do. Let me know if you're still running into issues.
