### ISSUE TITLE
ValueError: The following unexpected fields should be prefixed with an underscore: sentence_start.

### ISSUE THREAD

**Issue by desothier1** [dwadden/dygiepp#53]
Hi,

this is the first time I use dygiepp, so I am quite unexperienced.

I used the processed ace-event dataset
when starting the training I get error

ValueError: The following unexpected fields should be prefixed with an underscore: sentence_start.

one of the fields in the used .json files is 
"sentence_start"..."

In document.py I find

        "Make sure we only have allowed fields."
        allowed_field_regex = ("doc_key|dataset|sentences|weight|.*ner$|"
                               ".*relations$|.*clusters$|.*events$|^_.*")

Prefixing sentence_start  with underscore yields another error message

Thanks for helping me out

**Comment by dwadden** [comment]
Did you get this working? What was the error message after you prefixed `sentence_start` with an underscore?
