### ISSUE TITLE
Question about the number of documents of ACE2005 event extraction

### ISSUE THREAD

**Issue by yhcc** [dwadden/dygiepp#56]
Thanks for making a comprehensive summarization of Event Extraction pre-processing.

I am confused by the number of documents for each split.  File dev.filelist, test.filelist and train.filelist have 28, 40, 529 lines, which in total makes 597 documents, but Table 8 in the Appendix depicts there are 599 documents.

**Comment by dwadden** [comment]
Hi,

Hmm you're right, thanks for pointing this out. I got the splits from the authors of this paper (see Table 2 for statistics): https://arxiv.org/pdf/1609.03632.pdf.

I think what happened was that two of the test documents ID's didn't match any documents in my ACE distribution, so I removed them from `test.filelist`. Unfortunately, that's all the information I have; I worked on this project two years ago now so I don't remember all the details of the data preprocessing.

Dave
