### ISSUE TITLE
_normalize_word method in IEJsonReader class

### ISSUE THREAD

**Issue by ghtaro** [dwadden/dygiepp#6]
Hi dwadden,

thank you very much for uploading your code in github.
I have succeeded in running and training your model in my env following your instruction.

I have just noticed that _normalized_word method does NOT take "self" argument.
Given the model seems working, so it is not a big deal, but just let me report this for your reference.

**Comment by dwadden** [comment]
Thanks for the message! 
This is actually the desired behavior. The `_normalize_word` method has a `@staticmethod` decorator, which means the method shouldn't take a `self` argument: https://docs.python.org/3/library/functions.html#staticmethod.

**Comment by ghtaro** [comment]
Understood, thank you very much!
