### ISSUE TITLE
Scripts have inconsistent relative paths

### ISSUE THREAD

**Issue by david-waterworth** [dwadden/dygiepp#69]
The `get_genia.sh` scripts defines `out_dir=data/genia` so appears to expect the root folder to be /scripts

```
echo "Downloading raw GENIA data."
download_raw > $log_dir/00-download-genia.log
```

But later when it runs the various python scripts they're relative to the repo root ie.

```
echo "Splitting GENIA docs into folds."
python ./scripts/data/genia/split_folds.py > $log_dir/03-split-folds.log
```

I would say they probably both should be relative to the folder the scripts are in, but doesn't really matter - but at the moment they don't run at all without editing.

**Comment by david-waterworth** [comment]
Actually looking closer it appears the out_dir should be `out_dir=./data/genia` rather than `out_dir=data/genia` and the scirpts run from the repo root?

**Comment by dwadden** [comment]
Thanks for the heads up, I'll take a look at this tomorrow or in the next few days.

**Comment by david-waterworth** [comment]
Also, I found it convenient to create a `setup.py` in the root. This way instead of adding the source folder to you path you can install using `pip install -e .` to install in editable mode.

I find this works a bit better with virtual envs, particularly when using vscode. 

```
import os
from setuptools import setup, find_packages

def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

setup(
    name='dygie',
    version='1.0.0',
    description='DyGIE++',
    author='David Wadden',

    packages=find_packages(),

    long_description=read('README.md'),
    license='MIT License',
    install_requires=[
        'allennlp==1.1.0',
        'allennlp_models==1.1.0',
        'pandas==0.25.2',
        'beautifulsoup4==4.8.1',
        'lxml',
        'python-Levenshtein',
        'optuna>=2.1.0'
    ],
)
```

**Comment by dwadden** [comment]
Re `get_genia`: It works fine for me when run from the root folder of the project, as specified in the [README](https://github.com/dwadden/dygiepp/blob/master/README.md#genia). If it's not working for you, feel free to post the error message you're getting and I can try to debug.

Re `setup.py`: Looks good to me. Feel free to submit a PR, updating the `README` with the new installation instructions, and I'll merge.

**Comment by david-waterworth** [comment]
I ran it again and it's working, I must have been doing something wrong the first time around - probably running from the scripts rather than root folder of the project. 

I'll submit a PR once i have time to properly clone the repo. I also noticed a link to docs rather than doc somewhere in the readme so I'll refind and fix that at the same time.

**Comment by dwadden** [comment]
Sounds good, thanks!
