### ISSUE TITLE
Missing events config template

### ISSUE THREAD

**Issue by marchbnr** [dwadden/dygiepp#7]
Hi,
thank you very much for providing your source code!
I know that training on ace events is wip but if you would push your [local template](https://github.com/dwadden/dygiepp/blob/master/training_config/events_dw.jsonnet#L3) we could try to figure out how to train in the meantime

**Comment by dwadden** [comment]
Sorry for the slow reply. You should be able to use this file: https://github.com/dwadden/dygiepp/blob/master/training_config/template_dw.libsonnet.
