### ISSUE TITLE
Version of SpaCy for building ACE datasets

### ISSUE THREAD

**Issue by jmicher** [dwadden/dygiepp#75]
I'm trying to rebuild the ACE datasets according to instructions here: https://github.com/dwadden/dygiepp#creating-the-dataset-1
but apparently my institution is blocking my access to download via the command "python -m spacy download en"
Can you post which version of SpaCy is required so I can obtain it some other way?
Thanks

**Comment by dwadden** [comment]
The version of Spacy is specified in the [requirements.txt](https://github.com/dwadden/dygiepp/blob/master/scripts/data/ace-event/requirements.txt) file. In this case, it looks like you need `spacy==2.0.18`. Best of luck!
