### ISSUE TITLE
Genia dataset for Event Annotations 

### ISSUE THREAD

**Issue by Toan-it-mta** [dwadden/dygiepp#82]
I see in "https://github.com/dwadden/dygiepp/blob/master/doc/data.md#preprocesing-details-for-existing-datasets" mentioned dataset Genia can use to Event Annotations . I would like to ask, does your code currently support Genia data preprocessing for the Event Annotations  task? If yes, how to do?

Thanks

**Comment by dwadden** [comment]
The code does not support GENIA for events, if I recall. I'd welcome a pull request, though!
One challenge with GENIA is that event arguments can themselves be other events, and it's not totally intuitive how to cast this as a span-level task. One possible way to do this:
Suppose there's an event `A`, triggered by span `t_a`, and event `B`, triggered by `t_b`. If event `B` is an argument for event `A`, then use the span `t_b` to represent event `B` as the argument for `A`. 
Let me know if this makes sense.

**Comment by Toan-it-mta** [comment]
Thanks for the answer and suggestion from you. I am new in this field. I will try your suggestion and ask for permission to close the issue.

**Comment by dwadden** [comment]
Sure, sounds good. If you decide to attempt a PR, let me know and I'm happy to try and help if I can.
