### ISSUE TITLE
train model with new event tags

### ISSUE THREAD

**Issue by unlimit11** [dwadden/dygiepp#85]
hi, thanks for sharing your interesting project and idea.
i want to train the event classification model based on a new dataset that labels are different from ace.
please advise how can I introduce the available event tags to the model?

**Comment by dwadden** [comment]
Hi,

You can write your own preprocessing code to get the dataset into the format DyGIE++ expects, and then run the ACE event training script, but with the file paths changed to point to your new data.

For more info, see the [Working with new datasets](https://github.com/dwadden/dygiepp#working-with-new-datasets) section of the README, and also the doc describing the [data](https://github.com/dwadden/dygiepp/blob/master/doc/data.md). Let me know if you have specific questions.
