### ISSUE TITLE
environment.yml instead of requirements.txt?

### ISSUE THREAD

**Issue by serenalotreck** [dwadden/dygiepp#97]
I'm using dygiepp within a project I'm working on, and I was wondering if there's a reason why there's a `requirements.txt` file installed with pip, instead of a `environment.yml` file that installs packages with conda, since a conda environment is built. I've been having issues where when I try and install new packages with conda that I use in other code in the project, and I get dependency conflicts that pip's dependency resolver can't fix. I'm not totally sure if having the original environment be built with a conda `environment.yml` would fix that, but I've always understood that using pip in a conda environment is something you shouldn't so unless you can't avoid it. Wondering what your thoughts are?

**Comment by dwadden** [comment]
I think you're right, pip within conda is discouraged. I'd definitely accept a PR that relies solely on conda using an `environment.yml` file. 
Alternatively, you can just force pip to install your packge with the [--no-deps](https://stackoverflow.com/questions/12759761/pip-force-install-ignoring-dependencies) flag, which is the go-to strategy to ensure high-quality, reproducible research 😅 .
