### ISSUE TITLE
Training dygie on custom data converted from brat format to scierc format

### ISSUE THREAD

**Issue by Kehindeajayi01** [dwadden/dygiepp#98]
> In your example, one of your `relations` has value `[109, 109, null, null, "has_unit"]`. The code is breaking due to the presence of `null` values. See [data.md](https://github.com/dwadden/dygiepp/blob/master/doc/data.md) on the required format for input data.

The null were introduced by your brat_input.py script when I used it to convert the brat format to your format

_Originally posted by @Kehindeajayi01 in https://github.com/dwadden/dygiepp/issues/92#issuecomment-1071645445_

**Comment by dwadden** [comment]
Got it; re-opening previous issue.
